### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by FrederikSchorr** [dlpbc/keras-kinetics-i3d#3]
Hi dlpbc, your i3d keras model is awesome! 

I am working on sign language recognition for deaf-mute-people, and need to finetune the provided model/weights on another video-dataset.

In case you have also trained/finetuned with I3D - Could you share a training/finetuning script? I am in particular interested in data_generator needed for fitting with data augmentation.

Thank you! br Frederik

**Comment by dlpbc** [comment]
Thank you Frederik!

I don't have a training/finetuning script.

**Comment by ovesreinier** [comment]
Hi everyone
I am also trying to finetune the model but results are not so good as using the i3d-tensorflow implementation. Do you have any finetune code ?
Regards

**Comment by srijandas07** [comment]
check @srijandas07 for I3D training codes @FrederikSchorr

**Comment by Tortoise17** [comment]
Where can I get the .h5 weights for the inception i3d?
