### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by FrederikSchorr** [dlpbc/keras-kinetics-i3d#4]
Hello @dlpbc ,

I just wanted to thank you for porting the I3D network to Keras. I used it to build a Sign Language Recognition prototype: https://github.com/FrederikSchorr/sign-language

Kind regards, Frederik

PS: In https://github.com/FrederikSchorr/sign-language/blob/master/model_i3d.py I added a function `add_i3d_top` that creates new top layers depending on the number of output classes.

**Comment by comratvlad** [comment]
I would like to thank you too, your code has allowed me to save a lot of time to test the hypothesis and get closer to the desired result in my work. Thank you very much!

**Comment by dlpbc** [comment]
Thank you!

**Comment by tadbeer** [comment]
Hi @FrederikSchorr . Did you try finetuning I3D model on just RGB images too without the OFlow, for any dataset?
I am trying to finetune I3D on ucf-101, as per the methods specified in [paper](https://arxiv.org/abs/1705.07750), but am failing even after several iterations in hyperparameters.

**Comment by tadbeer** [comment]
Hi @comratvlad . Have you tried finetuning I3D model for any video dataset?
I am trying to finetune I3D on ucf-101, as per the methods specified in paper, but am failing even after several iterations in hyperparameters.
